### ISSUE TITLE
Boxes within CollapseBox lose margins

### ISSUE THREAD

**Issue by kyuhas** [open-olive/loop-development-kit#443] opened 2021-11-23 15:56 UTC
Hi, one of my whispers is using a large collapse box with some boxes inside. However,  I noticed that those boxes are losing their margins when placed within a collapse box. For example, in the code below, I have some boxes with a markdown inside. Outside of the collapse box, those boxes still have their marginBottoms. However, once placed within the collapse box, they lose their marginBottoms. Is this the intended behavior or can this be overwritten somehow so that I can retain the layout options of the components within the collapse box?

```
import { Direction, JustifyContent, StyleSize } from '@oliveai/ldk/dist/whisper';
import React from 'react';

export const TestCollapseBox = () => {
  return (
    <>
      <oh-box
        key="box-1"
        direction={Direction.Horizontal}
        justifyContent={JustifyContent.Left}
        layout={{ marginBottom: StyleSize.Large }}
      >
        <oh-markdown body="Test 1" />
      </oh-box>
      <oh-box
        key="box-2"
        direction={Direction.Horizontal}
        justifyContent={JustifyContent.Left}
        layout={{ marginBottom: StyleSize.Large }}
      >
        <oh-markdown body="Test 2" />
      </oh-box>
      <oh-collapse-box
        key="view-more-collapse-box"
        open
        label="View more"
        layout={{ marginTop: StyleSize.Small, marginBottom: StyleSize.Small }}
      >
        <oh-box
          key="box-3"
          direction={Direction.Horizontal}
          justifyContent={JustifyContent.Left}
          layout={{ marginBottom: StyleSize.Large }}
        >
          <oh-markdown body="Test 3" />
        </oh-box>
        <oh-box
          key="box-4"
          direction={Direction.Horizontal}
          justifyContent={JustifyContent.Left}
          layout={{ marginBottom: StyleSize.Large }}
        >
          <oh-markdown body="Test 4" />
        </oh-box>
      </oh-collapse-box>
    </>
  );
};
```
<img width="382" alt="OutsideOfCollapseBox" src="https://user-images.githubusercontent.com/26147799/143058206-23da3c7f-7df3-433d-b095-f5cb56591508.png">
<img width="380" alt="InsideCollapseBox" src="https://user-images.githubusercontent.com/26147799/143058222-92ea89e2-22d0-483e-a87e-074f2d91465c.png">

**Comment by BrettMugglinOlive** [comment] 2021-11-23 20:29
Hi @kyuhas ! I confirmed that indeed, it does appear that `Box` components in a `CollapseBox` aren't responding to the `layout` property applied to them, and I created HELPS-2383 to track it.

But, you may be able to work around this issue for the time being. Yes, `Box` components aren't rendering correctly in a `CollapseBox`. But, if you applied the same `layout` property on the `Markdowns` (or whatever the bottom element is) in the inner `Boxes`, you can get the desired effect. Now, doing this in the way that you have listed above, with `StyleSize.Large` applied to each `Markdown` component in your example doesn't quite give us what I'm guessing is the desired effect you're looking for. And it will look like this:

![Screen Shot 2021-11-23 at 12 16 30 PM](https://user-images.githubusercontent.com/77070962/143097376-00774b19-d023-4ae5-9292-b07120db7057.png)

The spacing between the different elements in here is still inconsistent, since there's too much spacing between Test 2 and Test 3, and too little between Test 3 and Test 4. This is dues to two reasons. One: Elements on the root level of a whisper by default have `0.5rem` of `margin-top` and Two: Elements in a `CollapseBox` don't have this default `margin-top`. So, the way that we would get around this and make the spacing consistent is to change Test 1's layout to `layout={{ marginBottom: StyleSize.Medium }}` and Test 2's layout to `layout={{ marginBottom: StyleSize.Small }}`. This would make your whisper look like this:

![Screen Shot 2021-11-23 at 12 24 17 PM](https://user-images.githubusercontent.com/77070962/143098394-3dc14065-141f-4825-8fc8-c521e2924a77.png)

In an ideal world, layout would look and render the same no matter where it's applied. I hesitate to open a ticket about the peculiarities described above though, cause it could impact other's layouts of their whispers in unforeseen ways. If this is something you would like addressed though, we can talk about it.

I know it's a bit hacky, and we will definitely fix the `Box` issue, but hopefully this helps!

**Comment by kyuhas** [comment] 2021-11-23 22:02
Hi @BrettMugglinOlive thanks for taking the time to provide this workaround! In my actual whisper, the components within the collapse box are pretty nested, but I was able to add the marginBottom to the lowest elements in the component, which worked. It would be nice if the box issue could be fixed so that I wouldn't have to create so many workarounds, but I definitely understand not wanting to mess up any current whispers!

**Comment by BrettMugglinOlive** [comment] 2022-01-24 23:09
HELPS-2383 has been fixed! Closing this thread, but if you feel that we need to address the other issue of root vs nested margins, feel free to reopen this or another thread.

**Closed by BrettMugglinOlive** 2022-01-24 23:09 UTC
Labels: Resolution: Complete, Type: Bug
