### ISSUE TITLE
Permissions changes do not take effect until loop reinstall

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#231] opened 2021-06-16 17:09 UTC
Whenever we change file system's pathGlobs we have to reinstall the loop for the changes to work. Can we make permissions update on restart?

**Comment by RusGraf** [comment] 2021-06-21 13:47
Hello Michael, yes the issue is that upon installation loop is copied to the internal OH folder and then metadata got built from it. So when you restart the loop it will use an internal copy. This request came up a couple of times and we have a card to capture this work. Although it is a lower priority.

**Comment by CandiceCLB** [comment] 2021-06-29 15:21
Updating the ticket number due to our board migration: HELPS-327

**Comment by CandiceCLB** [comment] 2021-09-08 18:36
Resolved with the release of OH v0.22.3

**Closed by CandiceCLB** 2021-09-08 18:36 UTC
Labels: Status: Assigned, Type: Enhancement
