### ISSUE TITLE
`Whisper` object from `whisper.create` doesn't have `components` and `close`

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#141] opened 2021-05-04 15:26 UTC
After we create a whisper with `whisper.create`, we can obtain a `Whisper` object. 
From the typescript interface definition, it should have a `close` function and a `components` property. However, these are all undefined.
```javascript
const newWhisper = await whisper.create({
  label: 'helloworld',
  components: [
    {
      type: whisper.WhisperComponentType.Markdown,
      body: 'Welcome!',
    },
  ],
  onClose: () => {},
});
console.info(`whisper.components: ${newWhisper.components}`);
console.info(`whisper.close: ${newWhisper.close}`);
```
If it is the intended behavior, how do we programmatically close a whisper?

**Comment by cshields-oliveai** [comment] 2021-05-04 18:13
@hans-hsieh-asus - as mentioned over in Discussions, this is not the intended behavior.

We have two tasks opened for each of these. We will update this Issue when a related change is made to the LDK.

**Comment by latman-oliveai** [comment] 2021-05-12 19:56
We are seeing impact from this issue too

**Comment by cshields-oliveai** [comment] 2021-05-18 14:04
@hans-hsieh-asus, @latman-oliveai  - This issue has been resolved in the most recent release of Olive Helps Olive Helps (V 0.17.3) and LDK (V 3.0.0.beta.3).

With the `Whisper` reference returned from `whisper.create()`, `close: (cb: (err: Error | undefined) => void) => void` can now be used as expected.

I will close this for now. If you are still experiencing any problems with this, you can create a new Github Issue.

**Closed by cshields-oliveai** 2021-05-18 14:04 UTC
Labels: Type: Enhancement
