### ISSUE TITLE
Data-binding with `<oh-text-input>` React component can cause re-rendering issues if user types too fast

### ISSUE THREAD

**Issue by kevinfiol** [open-olive/loop-development-kit#405] opened 2021-11-03 19:31 UTC
Following a common data-binding pattern with text inputs using the LDK's React components causes an issue where it appears delayed re-renders overwrite subsequent changes. Using data-binding is useful in our Loops when we'd like to programmatically "clear" the input by simply changing the bound variable in our state.

**Olive LDK Version**: 3.4.0

**Steps to reproduce:**
1. I created a simple component with a text input:
```tsx
import React, { useState } from 'react';

export const TexasFormularyWhisper = () => {
  const [state, setState] = useState('');

  return (
    <oh-whisper label={'Medicaid Formulary Search: Texas'} onClose={() => {}}>
      <oh-text-input
        label="hello"
        value={state}
        onChange={(_, val) => setState(val)}
      />

      <oh-markdown body={`User typed: ${state}`} />
    </oh-whisper>
  )
};
```

And rendered this Whisper component in a separate module:
```tsx
import * as ReactWhisper from '@oliveai/ldk/dist/whisper/react/renderer';
import { TexasFormularyWhisper } from './whisper';

(async () => {
  ReactWhisper.renderNewWhisper(<TexasFormularyWhisper />);
})();
```

2. If a user types too fast into this text input, letters can get chopped off. See the video for an example. It's a bit hard to see in my first attempt, but more clear on my second attempt:

https://user-images.githubusercontent.com/4752973/140179711-a56a6023-9be4-4a8f-af63-0868fd0d2952.mp4

Thanks @richseviora for providing more insight into this earlier this week.

**Comment by BrettMugglinOlive** [comment] 2021-11-03 23:45
Thanks for the example! If we're dropping the correct state at any point in time, that certainly would be a problem. But, I'm trying to get the behavior that you're describing to happen locally, but I'm not seeing it. I do have a couple of thoughts / observations though (not trying to dismiss this as a possible bug).

1. In trying to get this bug to trigger, I would run my finger along a row of my keyboard, back and forth. This was inputting characters faster than what it looks like in your video, yet I was unable to get a similar result of characters missing.
2. Why I might not be able to reproduce it might be because this isn't a logic bug with the component itself, but a performance bug with the system. What kind of specs does your computer have?

**Comment by kevinfiol** [comment] 2021-11-04 16:04
Hey @BrettMugglinOlive , thanks for taking a look.

Indeed, it may be related to performance. I notice the issue is more prevalent when I have more whispers open or a whisper with several elements to render.

My system is a Dell XPS 13 2020; *however*, since I am on Ubuntu, I must run Olive Helps in a Windows VM, which has 8GB of RAM, and access to 2 cores of the host PC's i9-10885H cores (@ 5.3Ghz). I briefly allocated 8 cores to my VM and bumped the RAM to 16GB, but still experienced the issue. Maybe inherent performance repercussions to using OH in VMWare?

I notice the issue more clearly in this simplified version of a Feedback whisper we have with multiple bound variables:

```tsx
export const Feedback = () => {
  const [inputs, setInputs] = useState({
    feedbackFormName: '',
    feedbackFormEmail: '',
    feedbackFormFeedback: '',
  });

  const handleInput = (key: string, value: string) => {
    setInputs((inputs) => ({
      ...inputs,
      [key]: value,
    }));
  };

  return (
    <oh-box direction={whisper.Direction.Vertical} justifyContent={whisper.JustifyContent.Center}>
      <oh-text-input
        id="feedbackFormName"
        label="Your Name"
        value={inputs.feedbackFormName}
        onChange={(_, val) => handleInput('feedbackFormName', val)}
      />

      <oh-text-input
        id="feedbackFormEmail"
        label="Email Address"
        value={inputs.feedbackFormEmail}
        onChange={(_, val) => handleInput('feedbackFormEmail', val)}
      />

      <oh-text-input
        id="feedbackFormFeedback"
        label="Feedback"
        value={inputs.feedbackFormFeedback}
        onChange={(_, val) => handleInput('feedbackFormFeedback', val)}
      />
    </oh-box>
  );
};
```

Out of curiosity, I tested [a vanilla React equivalent](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqEAB585AG4ACcvgC8AHRA5sygHyiA9BMnqQAXyL0mLEKwBW1EpAFDOI2zE7SAgtmzT50gBQBKL3VpYEUoaWknFxpyKGwAV04YImk8TgBJWISYAF0vaQAlREwwTlY4vABlTkxBHxCw8OloRBRpAHI2olDG6U4AdwhWjq6G8M52ACdEFva27ukDPwBuefmnBERWeAgAcx8Y+MTl1YbI6XZMKHwkDMO8nwBrRABPZMlMeDjEAPkg+p7UrcsvtMolAr5-j1pKwYQcsiModIaE9ntlWu9Poh5uFFscGgYVg15lNOHEJmEfNjpOIpOoqeFRHDOPTGpxnthEEoQIIAB7MkAs8IYr7yYBMmCsZoGQVNKAAYQuUB2nOAPkQkh+QUV10QQM4PjazU60nVrGqE2VpWF32lo0aWjpdvCLMZoJlbI5XN5-Jl1tF4rNA1tiPC0AVl2VorVGvB2puoIN-QgxtN5strGtfmDUIdLJdTPd7M5ym9yl9HxFYtBEvGU0Q2cRYcVkdV6s150uOr1icm0xTkjNmAtiCtFZtLNzTukLoARglONBZXL4OQwA8o+3AdW6rKZsNegMhsba9Mjwss46Q9Jl0UJi6tHPOAuoJfGtpdK+8QTQqFCsVOAAIgA8gAsqwUxXIgEyUlAiicKI7ieJOySqH4fCQIw2CUFBIgzpgM6ILwJB4EgJTkNA1BoAAzAAHCgACMACshjGCADDMCIrBgDA1j8IIwhoEywTSH0cjjK09EAAySQApEsCx8CRiBkRRIiSSgABMkmGNkJArlADyUXQbGmCIUz-nwZK8GgXCcLgKBaFocSxA8OxcRAjBaOZJROYw+BeUUJSsPg6qERA2DMAIli8R6ZgwGAEzkNgDhGCYHFoN5nAALT4B5lkTNZIC2fZjnOdgrnuZ5mU5R5vn+dVuWMMFoXbBF9jRXwsUiPFiXJTpBhAA) in Edge browser on my VM, but was not able to replicate the issue there.

Please let me know if there's anymore information I can provide to help diagnose this issue.

**Comment by BrettMugglinOlive** [comment] 2021-11-04 23:04
Hmm...I still don't seem to be able to replicate the bug. I'll have someone who has a windows machine give it a go and see if it happens for them.

**Comment by kyuhas** [comment] 2021-11-08 20:40
Hi! I just wanted to reach out because I am experiencing a similar issue. Attached is some test code and a video to show the issue. In the video, I am typing "this is a test I am typing really quickly", but that isn't what is showing up because some of the letters get cut off.

```
import { Direction, JustifyContent } from '@oliveai/ldk/dist/whisper';
import React, { useState } from 'react';

export const Example = () => {
  const [value, setValue] = useState('');

  return (
    <oh-box direction={Direction.Vertical} justifyContent={JustifyContent.Left}>
      <oh-text-input label="testing" onChange={(_, val) => setValue(val)} value={value} />
    </oh-box>
  );
};

```

https://user-images.githubusercontent.com/26147799/140814892-4984ae25-2802-4df6-875a-64e1069f2e29.mov

**Comment by BrettMugglinOlive** [comment] 2021-11-23 22:06
@kyuhas @kevinfiol Perhaps I'm not as fast a typist as both of you but even with the example provided in the previous comment, typing what you typed I still can't seem to make it happen locally. I'll attach a recording of what I saw. Note, that I am on a Macbook Pro with 16GB RAM and a 2.6 GHz 6-core i7 processor. 

@kyuhas Are you also working through a VM when you see this issue occur?

https://user-images.githubusercontent.com/77070962/143136680-1c4561bb-79d2-47e1-8c78-8d6bc68838ec.mov

**Comment by kyuhas** [comment] 2021-11-23 23:56
@BrettMugglinOlive No, I am not working through a VM when I see that issue. I'm on a Macbook Pro with 32 GB RAM and a 2.3 GHz 8-Core Intel Core i9 processor. I noticed that it's kind of inconsistent. If I type super quickly, I'll usually see it, but if I'm typing at a slightly slower pace, I'll only sometimes see it. Other times, I could be typing very slowly and still see it (e.g. if I clear out all the text and then start typing again).

**Comment by BrettMugglinOlive** [comment] 2021-11-24 22:11
@kyuhas @kevinfiol Alright, so I worked with @MaggieMaSS, and she was able to reproduce the issue that you are showing. For what it's worth, the only spec difference between our Macbooks seems to be that I have a 4GB graphics card, and she has a 1.7GB one. 

Our theory is that this is a problem rooted in React and Olive Helps competing with each other for updates in a race condition. Every time you call `setValue` React re-renders, and causes a Whisper update to occur. By the time the update occurs and pushes data back up, if you're typing fast enough, the UI is in a more current state than what the Whisper thinks it is...or something along those lines. I haven't identified the true root cause yet, but this seems plausible. I creates HELPS-2400 to address this.

But, you're in luck, cause we also identified a (hacky) workaround for this problem! Ultimately, this is a timing issue. So, we just need to change the timing of the sequence of events a bit to fix the UX while still holding onto the value. I used some timeouts in order to shift the call to `setValue` to occur only after the user had stopped typing for some period of time. I confirmed that this fixed the issue on @MaggieMaSS's environment. 

Hopefully this is a good enough workaround for now, because I think finding and fixing the root cause of this might be a bit of a bear. Let me know if this works / if you have any other questions!

The hax:
```import { Direction, JustifyContent } from '@oliveai/ldk/dist/whisper';
import React, { useState } from 'react';

export const Example = () => {
  const [value, setValue] = useState('');

  let t = setTimeout(() => {
    // do nothing
  }, 0);

  return (
    <oh-box direction={Direction.Vertical} justifyContent={JustifyContent.Left}>
      <oh-text-input
          label="testing"
          onChange={(_, val) => {
            clearTimeout(t);
            t = setTimeout(() => {
              setValue(val);
            }, 500);
          }}
          value={value}
      />
    </oh-box>
  );
};```

**Comment by kevinfiol** [comment] 2021-11-24 22:25
@BrettMugglinOlive I'm glad you guys were able to replicate it! We have been debouncing the state updates as a work around for now as well. While it's not a seamless workaround, it definitely improves the experience.

**Comment by ssteuteville** [comment] 2021-12-27 22:19
I was able to reproduce this outside of react whispers. I'm on one of the new m1 macs with 32gb ram.

Our whisper is fairly complex and I have more than one open.

The debounce trick works for now, but would love to see this fixed!

**Comment by BrettMugglinOlive** [comment] 2022-01-24 20:05
@kevinfiol @kyuhas @ssteuteville So, we've been looking into this issue, but have ultimately decided to not fix it for the time being. It seems like the issue (which can be more easily seen on slower hardware) is a race condition between what the internal value in Olive Helps of an input is vs. what the external (what you're holding in state) is. 

The recommendation from the UI team is to only update your local state's value in the `onChange` function, and not pass in a `value` attribute unless you are trying to programmatically change that input's value. But, if debouncing is working, then that is fine too!

I'm going to close this thread for now, but feel free to reopen it if you feel strongly that we need to address this issue.

**Closed by BrettMugglinOlive** 2022-01-24 20:05 UTC
Labels: Resolution: Wontfix, Type: Bug
