### ISSUE TITLE
Stop listening for hotkey

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#154] opened 2021-05-06 03:30 UTC
With LDK3, I can listen for hotkey with
```javascript
keyboard.listenHotkey({
  key: 'i',
  control: true,
}, (pressed) => {});
```
But how do I *unlisten* for the hotkey?

**Comment by cshields-oliveai** [comment] 2021-05-06 13:05
@hans-hsieh-asus - This was planned for our current iteration and we have completed work to handle cancelling listeners from the LDK. You can view the pull request [here](https://github.com/open-olive/loop-development-kit/pull/111).

There is a bit more work to be done on the Olive Helps side for this implementation, but you can expect to be able to cancel any kind of listener with our next release.

**Comment by cshields-oliveai** [comment] 2021-05-18 14:10
@hans-hsieh-asus - With the most recent release of Olive Helps (V 0.17.3) and LDK (V 3.0.0.beta.3), all listeners return `Promise<Cancellable>`. This will allow you to call `cancel()` to close out streams.

I am closing this issue. As always, if you are seeing any unintended behavior please open a new Issue.

**Closed by cshields-oliveai** 2021-05-18 14:10 UTC
Labels: Type: Question
